[2024-10-11 10:16:20,382 (/home/ubuntu/FIKA_WCS/db_redis/handle_redis.py:33 - __init__())] INFO -> Connect redis successful
[2024-10-11 10:16:20,453 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:55 - __connect())] INFO -> Successfully connected to PLC at 192.168.31.3:502
[2024-10-11 10:16:20,453 (/home/ubuntu/FIKA_WCS/PLC/plc_controller.py:149 - __check_trigger())] INFO -> START CHECK PLC
[2024-10-11 10:16:20,834 (/home/ubuntu/FIKA_WCS/apis/DAL/DAL_server.py:44 - get_token_bearer_backend())] ERROR -> Get token error: 'metaData'
[2024-10-11 10:16:25,921 (/home/ubuntu/FIKA_WCS/apis/DAL/DAL_server.py:44 - get_token_bearer_backend())] ERROR -> Get token error: 'metaData'
[2024-10-11 10:16:31,009 (/home/ubuntu/FIKA_WCS/apis/DAL/DAL_server.py:44 - get_token_bearer_backend())] ERROR -> Get token error: 'metaData'
[2024-10-11 10:16:36,098 (/home/ubuntu/FIKA_WCS/apis/DAL/DAL_server.py:44 - get_token_bearer_backend())] ERROR -> Get token error: 'metaData'
[2024-10-11 10:16:41,186 (/home/ubuntu/FIKA_WCS/apis/DAL/DAL_server.py:44 - get_token_bearer_backend())] ERROR -> Get token error: 'metaData'
[2024-10-11 10:16:46,275 (/home/ubuntu/FIKA_WCS/apis/DAL/DAL_server.py:44 - get_token_bearer_backend())] ERROR -> Get token error: 'metaData'
[2024-10-11 10:16:51,363 (/home/ubuntu/FIKA_WCS/apis/DAL/DAL_server.py:44 - get_token_bearer_backend())] ERROR -> Get token error: 'metaData'
[2024-10-11 10:16:56,452 (/home/ubuntu/FIKA_WCS/apis/DAL/DAL_server.py:44 - get_token_bearer_backend())] ERROR -> Get token error: 'metaData'
[2024-10-11 10:17:01,541 (/home/ubuntu/FIKA_WCS/apis/DAL/DAL_server.py:44 - get_token_bearer_backend())] ERROR -> Get token error: 'metaData'
[2024-10-11 10:18:12,468 (/home/ubuntu/FIKA_WCS/db_redis/handle_redis.py:33 - __init__())] INFO -> Connect redis successful
[2024-10-11 10:18:12,537 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:55 - __connect())] INFO -> Successfully connected to PLC at 192.168.31.3:502
[2024-10-11 10:18:12,537 (/home/ubuntu/FIKA_WCS/PLC/plc_controller.py:149 - __check_trigger())] INFO -> START CHECK PLC
[2024-10-11 10:18:12,917 (/home/ubuntu/FIKA_WCS/apis/DAL/DAL_server.py:42 - get_token_bearer_backend())] INFO -> Get token seccessful message.
[2024-10-11 10:18:12,945 (/home/ubuntu/FIKA_WCS/agv/agv_manager.py:17 - __init__())] INFO -> START AGV
[2024-10-11 10:18:12,948 (/home/ubuntu/FIKA_WCS/DWS/handle_dws.py:19 - __sub_request())] INFO -> START CHECK DWS
[2024-10-11 10:18:12,953 (/home/ubuntu/FIKA_WCS/markem_printer/printer_manager.py:24 - __sub_print_request())] INFO -> START PRINT MARKEM
[2024-10-11 10:18:12,954 (/home/ubuntu/FIKA_WCS/datamax_printer/printer_manager.py:21 - __sub_print_request())] INFO -> START REPRINT
[2024-10-11 10:18:12,955 (/home/ubuntu/FIKA_WCS/socket_tcp/socket_tcp_interface.py:47 - connect())] INFO -> Connected to 192.168.31.210:9100
[2024-10-11 10:18:12,955 (/home/ubuntu/FIKA_WCS/tranfer/control_tranfer.py:19 - __init__())] INFO -> TRANFER READY
[2024-10-11 10:18:12,956 (/home/ubuntu/FIKA_WCS/tasks/scheduler.py:13 - __run_schedule())] INFO -> SCHEDUAL START
[2024-10-11 10:18:12,963 (/home/ubuntu/FIKA_WCS/apis/__init__.py:39 - start())] INFO -> RestAPI READY
[2024-10-11 11:30:43,421 (/home/ubuntu/FIKA_WCS/apis/DAL/DWS_api.py:36 - post())] ERROR -> DWS error connect: Time since last heartbeat is 4350.50 seconds
[2024-10-11 13:41:52,863 (/home/ubuntu/FIKA_WCS/db_redis/handle_redis.py:33 - __init__())] INFO -> Connect redis successful
[2024-10-11 13:41:52,931 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:55 - __connect())] INFO -> Successfully connected to PLC at 192.168.31.3:502
[2024-10-11 13:41:52,931 (/home/ubuntu/FIKA_WCS/PLC/plc_controller.py:149 - __check_trigger())] INFO -> START CHECK PLC
[2024-10-11 13:41:53,315 (/home/ubuntu/FIKA_WCS/apis/DAL/DAL_server.py:42 - get_token_bearer_backend())] INFO -> Get token seccessful message.
[2024-10-11 13:41:53,341 (/home/ubuntu/FIKA_WCS/agv/agv_manager.py:17 - __init__())] INFO -> START AGV
[2024-10-11 13:41:53,343 (/home/ubuntu/FIKA_WCS/DWS/handle_dws.py:19 - __sub_request())] INFO -> START CHECK DWS
[2024-10-11 13:41:53,346 (/home/ubuntu/FIKA_WCS/markem_printer/printer_manager.py:24 - __sub_print_request())] INFO -> START PRINT MARKEM
[2024-10-11 13:41:53,347 (/home/ubuntu/FIKA_WCS/socket_tcp/socket_tcp_interface.py:47 - connect())] INFO -> Connected to 192.168.31.210:9100
[2024-10-11 13:41:53,348 (/home/ubuntu/FIKA_WCS/datamax_printer/printer_manager.py:21 - __sub_print_request())] INFO -> START REPRINT
[2024-10-11 13:41:53,349 (/home/ubuntu/FIKA_WCS/tranfer/control_tranfer.py:19 - __init__())] INFO -> TRANFER READY
[2024-10-11 13:41:53,350 (/home/ubuntu/FIKA_WCS/tasks/scheduler.py:13 - __run_schedule())] INFO -> SCHEDUAL START
[2024-10-11 13:41:53,357 (/home/ubuntu/FIKA_WCS/apis/__init__.py:39 - start())] INFO -> RestAPI READY
